### ISSUE TITLE
Addon creates LUA Failure and is not working.

### ISSUE THREAD

**Issue by sahnebar** [keysc3/MplusGains#13]
Hi, 

i tried to use this nice addon, but it won't work anymore. I don't know whats worng, so i'll post a screenshot and the Lua error messages. 

![alt text](https://i.imgur.com/Nyq6dhv.png)

Message: Interface/AddOns/MplusGains/DungeonInfo.lua:162: attempt to index field 'dungeonInfo' (a nil value)
Time: Mon Nov 20 18:21:40 2023
Count: 2
Stack: Interface/AddOns/MplusGains/DungeonInfo.lua:162: attempt to index field 'dungeonInfo' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/MplusGains/DungeonInfo.lua"]:162: in function `CalculateRating'
[string "@Interface/AddOns/MplusGains/MplusGains.lua"]:1225: in function <Interface/AddOns/MplusGains/MplusGains.lua:1224>
[string "@Interface/AddOns/MplusGains/MplusGains.lua"]:1295: in function <Interface/AddOns/MplusGains/MplusGains.lua:1270>

Locals: 

Message: Interface/AddOns/MplusGains/MplusGains.lua:199: bad argument #1 to 'pairs' (table expected, got nil)
Time: Mon Nov 20 17:55:03 2023
Count: 1
Stack: Interface/AddOns/MplusGains/MplusGains.lua:199: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/MplusGains/MplusGains.lua"]:199: in function <Interface/AddOns/MplusGains/MplusGains.lua:198>

Locals: 

Could you please help me. 
kind regards, 
Sahnebar

**Comment by keysc3** [comment]
@sahnebar Thanks for the report, I'll look into it.  Does this error occur when you initially boot the game/login to a character? Or is this only after a reload?

**Comment by sahnebar** [comment]
Yes. 

Now i deactivated all addons and when i try to use the addon it shows me the following error. 

Message: Interface/AddOns/MplusGains/MplusGains.lua:199: bad argument #1 to 'pairs' (table expected, got nil)
Time: Mon Nov 20 22:23:26 2023
Count: 1
Stack: Interface/AddOns/MplusGains/MplusGains.lua:199: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/MplusGains/MplusGains.lua"]:199: in function <Interface/AddOns/MplusGains/MplusGains.lua:198>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by keysc3** [comment]
I'm unable to replicate the errors on my end unfortunately. It's possible that the first error provided is a consequence of the second so for now I put out a new release with error checking that should resolve the last error you provided.

**Comment by sahnebar** [comment]
soo now i found the error... the error was the language :P so maybe i need to translate some dungeon names or something else. Maybe i can help you with this?
--> I play the game in german.

**Comment by keysc3** [comment]
Good find! I forgot to switch from English affix names to affix IDs for logic/indexing so it was throwing an error for non-English clients. I've pushed a release that fixes the error and the addon should now work for all selectable languages in the battle net client settings. Thank you for your help!
