### ISSUE TITLE
Massive number of lua errors after changing font/colors

### ISSUE THREAD

**Issue by reasonedtraveler** [keysc3/MplusGains#22]
**Describe the bug**
I received 9427 lua errors in just a couple of minutes when I logged in to WoW after installing MPG. I made changes to the font and colors last night before logging off. It seemed to work fine then, but then logging in today seemed to break everything. When I clicked to open MPG, only the header appeared and nothing else. Reinstalling and removing saved settings fixed it, but I'm not sure what is going on to cause the error. Another weird thing that might be a clue is that my wife installed MPG at the same time as I did. We're running the same version, but hers has additional options such as choosing class color and RBG color selection.  - Also, this addon is awesome!

**To Reproduce**
BugGrabber error report is below. FYI, there were no lua errors during this session other than the 9427 from MPG.

**Additional context**
9427x MplusGains/MplusGains.lua:2305: attempt to index local 'headerFrame' (a nil value)
[string "@MplusGains/MplusGains.lua"]:2305: in function <MplusGains/MplusGains.lua:2300>
[string "@MplusGains/MplusGains.lua"]:2377: in function <MplusGains/MplusGains.lua:2334>

Locals:
dungeonHolderFrame = nil
summaryFrame = nil
headerFrame = nil
(*temporary) = <function> defined @MplusGains/MplusGains.lua:263
(*temporary) = 9
(*temporary) = <table> {
 3 = <table> {
 }
 10 = <table> {
 }
 123 = <table> {
 }
}
(*temporary) = "attempt to index local 'headerFrame' (a nil value)"
weeklyAffix = 10
addon = <table> {
 CalculateChest = <function> defined @MplusGains/DungeonInfo.lua:211
 CreateKeystoneButton = <function> defined @MplusGains/KeystoneButton.lua:9
 fortifiedID = 10
 FormatTimer = <function> defined @MplusGains/FormatHelpers.lua:8
 RoundToOneDecimal = <function> defined @MplusGains/FormatHelpers.lua:23
 affixInfo = <table> {
 }
 GetPlayerDungeonBests = <function> defined @MplusGains/DungeonInfo.lua:72
 CalculateRating = <function> defined @MplusGains/DungeonInfo.lua:178
 GetOppositeAffix = <function> defined @MplusGains/DungeonInfo.lua:110
 tyrannicalID = 9
 GetWeeklyAffixInfo = <function> defined @MplusGains/DungeonInfo.lua:136
 GetGeneralDungeonInfo = <function> defined @MplusGains/DungeonInfo.lua:56
 SetNewBest = <function> defined @MplusGains/DungeonInfo.lua:304
 SortAffixesByLevel = <function> defined @MplusGains/DungeonInfo.lua:283
 SortDungeonsByScore = <function> defined @MplusGains/DungeonInfo.lua:223
 SortDungeonsByLevel = <function> defined @MplusGains/DungeonInfo.lua:243
 FormatDecimal = <function> defined @MplusGains/FormatHelpers.lua:32
 CalculateDungeonTotal = <function> defined @MplusGains/DungeonInfo.lua:27
 CalculateDungeonRatings = <function> defined @MplusGains/DungeonInfo.lua:40
 scorePerLevel = <table> {
 }
}
selectedAffix = 10
SetDesaturation = <function> defined @MplusGains/MplusGains.lua:263
PopulateAllDungeonRows = <function> defined @MplusGains/MplusGains.lua:1736
PopulateAllAffixRows = <function> defined @MplusGains/MplusGains.lua:1720
PopulateAllBestRunsRows = <function> defined @MplusGains/MplusGains.lua:2122

**Comment by keysc3** [comment]
Hey thanks for the bug report! It is likely that whatever font you chose was missing on your next boot up and is causing the errors. The error checking I did for fonts either isn't enough or not working as intended. I'll take a look into fixing it.

As for the additional options missing, was this when you had errors or after the reinstall?
