### ISSUE TITLE
Cannot select font in Asian clients

### ISSUE THREAD

**Issue by ahe-meow** [keysc3/MplusGains#31]
**Describe the bug**
By default this addon displays everything in a font "Friz Quadrata TT". It is an ASCII font or so, so every Wchar displays as a box.
Addon provide a option to select existing fonts. But doesn't give any reponses when clicking the font. The window, the dropbox, everything just stays open as the same as before clicking. And the font doesn't change.

**To Reproduce**
Just open the addon UI in Asian clients. Click the gear icon, then select font.

**Expected behavior**
It is supposed to selecte a font, thus change everything in the window.

**Screenshots**

**Additional context**
![微信图片_20240815115303](https://github.com/user-attachments/assets/3e1021c0-ce54-4c32-8f36-e055fd845196)

**Comment by keysc3** [comment]
Thanks for the report. I should be able to get a fix out tomorrow so that the default font is one supported by the users client locale and non-supported ones don't break the addon.

**Comment by keysc3** [comment]
A fix has been released.
